import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Search } from 'lucide-react'
import { Footer, Header, ProductCard, TrustBar } from '@/components/storefront'
import { getProducts } from '@/lib/products'

const brands = ['GM', 'Renault', 'MWM', 'Mitsubishi', 'Mercedes-Benz', 'Audi', 'Fiat', 'Volkswagen', 'Suzuki', 'Ford']
const types = [
  { key: 'roletado', name: 'Roletado', desc: 'Precisão e durabilidade para o seu motor', symbol: 'R' },
  { key: 'admissao', name: 'Admissão', desc: 'Fluxo eficiente para melhor desempenho', symbol: 'A' },
  { key: 'escape', name: 'Escape', desc: 'Resistência para altas temperaturas', symbol: 'E' },
  { key: 'conjunto', name: 'Conjunto eixo + balancins', desc: 'Tudo o que você precisa em um só kit', symbol: 'C' },
]

export default async function Home() {
  const featured = (await getProducts({ inStock: true })).slice(0, 8)
  return <div className="min-h-screen bg-white"><Header /><main>
    <section className="relative overflow-hidden bg-[#FAF8F3]"><div className="container grid min-h-[530px] items-center gap-12 py-16 lg:grid-cols-[1.08fr_.92fr] lg:py-20"><div className="animate-fade-up max-w-xl"><p className="mb-5 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-[#B58A2E]"><span className="h-px w-8 bg-[#B58A2E]" /> Especialistas em motores</p><h1 className="font-[var(--font-poppins)] text-4xl font-bold leading-[1.1] tracking-tight text-[#111] sm:text-5xl lg:text-[56px]">Tudo em balancim de válvula, <span className="text-[#B58A2E]">de quem é especialista</span></h1><p className="mt-6 max-w-md text-base leading-relaxed text-[#6B6B6B]">Peças de procedência para veículos leves e pesados. Encontre o balancim certo para o seu motor.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/produtos" className="inline-flex h-12 items-center gap-2 rounded bg-[#B58A2E] px-6 text-sm font-semibold text-white transition hover:bg-[#8e6b20]">Ver catálogo <ArrowRight className="size-4" /></Link><a href="https://wa.me/5500000000000" target="_blank" rel="noreferrer" className="inline-flex h-12 items-center rounded border border-[#D4B05A] px-6 text-sm font-semibold text-[#111] transition hover:bg-white">Falar com especialista</a></div><div className="mt-10 flex items-center gap-5 text-xs text-[#6B6B6B]"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#B58A2E]" /> Garantia de procedência</span><span className="hidden items-center gap-2 sm:flex"><CheckCircle2 className="size-4 text-[#B58A2E]" /> Envio nacional</span></div></div><div className="relative mx-auto flex w-full max-w-[460px] items-center justify-center"><div className="absolute aspect-square w-[88%] rounded-full border border-[#D4B05A]/40" /><div className="absolute aspect-square w-[68%] rounded-full border border-[#D4B05A]/30" /><div className="relative flex aspect-square w-[74%] items-center justify-center overflow-hidden rounded-full bg-white shadow-[0_20px_70px_rgba(181,138,46,0.12)]"><Image src="/logo-casados-balancim.png" alt="Casa dos Balancim" fill className="object-contain p-8" priority /></div></div></div><div className="container pb-8 lg:pb-12"><form action="/produtos" className="mx-auto flex max-w-3xl items-center rounded border border-[#E7E7E5] bg-white p-2 shadow-lg shadow-[#111]/5"><Search className="ml-3 size-5 text-[#B58A2E]" /><input name="q" className="h-12 min-w-0 flex-1 bg-transparent px-3 text-sm text-[#111] outline-none placeholder:text-[#6B6B6B]" placeholder="Busque por aplicação, veículo ou motor..." /><button className="hidden h-12 rounded bg-[#111] px-6 text-sm font-semibold text-white transition hover:bg-[#B58A2E] sm:block">Buscar peça</button></form></div></section>
    <section className="container py-16 sm:py-20"><div className="mb-8 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#B58A2E]">Encontre com facilidade</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-[#111] sm:text-3xl">Compre por linha</h2></div><Link href="/produtos" className="hidden items-center gap-1 text-sm font-semibold text-[#B58A2E] sm:flex">Ver todas <ArrowRight className="size-4" /></Link></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-5 lg:gap-4">{brands.map((brand, i) => <Link href={`/produtos?montadora=${encodeURIComponent(brand)}`} key={brand} className="group flex min-h-[112px] flex-col items-center justify-center gap-3 rounded border border-[#E7E7E5] bg-white transition hover:border-[#D4B05A] hover:bg-[#FAF8F3] hover:shadow-sm"><span className="font-[var(--font-poppins)] text-xl font-bold text-[#B58A2E] transition group-hover:scale-110">{brand === 'Mercedes-Benz' ? 'MB' : brand.slice(0, 2).toUpperCase()}</span><span className="text-xs font-medium text-[#6B6B6B]">{brand}</span></Link>)}</div></section>
    <section className="bg-[#FAF8F3] py-16 sm:py-20"><div className="container"><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#B58A2E]">A peça que você procura</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-[#111] sm:text-3xl">Compre por tipo</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{types.map(type => <Link href={`/produtos?categoria=${type.key}`} key={type.key} className="group rounded border border-[#E7E7E5] bg-white p-6 transition hover:-translate-y-1 hover:border-[#D4B05A] hover:shadow-md"><span className="flex size-12 items-center justify-center rounded-full bg-[#FAF8F3] font-[var(--font-poppins)] text-xl font-bold text-[#B58A2E] group-hover:bg-[#D4B05A]/20">{type.symbol}</span><h3 className="mt-5 text-base font-semibold text-[#111]">{type.name}</h3><p className="mt-2 text-sm leading-relaxed text-[#6B6B6B]">{type.desc}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-[#B58A2E]">Explorar <ArrowRight className="size-3" /></span></Link>)}</div></div></section>
    <section className="container py-16 sm:py-20"><div className="mb-8 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#B58A2E]">Seleção da casa</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-[#111] sm:text-3xl">Destaques</h2></div><Link href="/produtos" className="flex items-center gap-1 text-sm font-semibold text-[#B58A2E]">Ver catálogo <ArrowRight className="size-4" /></Link></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 lg:gap-5">{featured.map(product => <ProductCard key={product.id} product={product} />)}</div></section>
    <TrustBar />
  </main><Footer /></div>
}
